github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
# added after https://conda-forge.org/blog/2020/10/29/macos-arm64 in order to
# build the package for osx-arm64
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
